import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const robotoSans = Roboto({
  subsets: ["vietnamese"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "TableIO",
  description: "Generated by TableIO",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoSans.className}>{children}</body>
    </html>
  );
}
